[WithATS]

# parameters for repeated values: 
# video-streams: videoCIR, videoCBS
# lidare-streams: lidarCIR, lidarCBS
# devices with sources: deviceOverhead
# switches: switchOverhead
 

# ATS on devices
# Camera Front & Rear

*.camera*.hasEgressTrafficFiltering = true
*.camera*.bridging.streamFilter.egress.meter[0].typename = "EligibilityTimeMeter"
*.camera*.bridging.streamFilter.egress.filter[0].typename = "EligibilityTimeFilter"

*.cameraFront.bridging.streamFilter.egress.numStreams = 1
*.cameraFront.bridging.streamFilter.egress.classifier.mapping = {"SVideoFront": 0}
*.cameraFront.bridging.streamFilter.egress.*[0].display-name = "SVideoFront"
*.cameraRear.bridging.streamFilter.egress.numStreams = 1
*.cameraRear.bridging.streamFilter.egress.classifier.mapping = {"SVideoRear": 0}
*.cameraRear.bridging.streamFilter.egress.*[0].display-name = "SVideoRear"
*.camera*.bridging.streamFilter.egress.meter[0].committedInformationRate = ${videoCIR = 200}Mbps
*.camera*.bridging.streamFilter.egress.meter[0].committedBurstSize = ${videoCBS = 1426}B 
*.camera*.bridging.streamFilter.egress.meter[0].packetOverheadLength = ${deviceOverhead = 32}B

*.camera*.eth[0].macLayer.queue.queue[5].typename = "EligibilityTimeQueue"
*.camera*.eth[0].macLayer.queue.transmissionSelectionAlgorithm[5].typename = "EligibilityTimeGate"

# Lidars
*.lidar*.hasEgressTrafficFiltering = true
*.lidar*.bridging.streamFilter.egress.meter[0].typename = "EligibilityTimeMeter"
*.lidar*.bridging.streamFilter.egress.filter[0].typename = "EligibilityTimeFilter"

*.lidarFrontLeft.bridging.streamFilter.egress.numStreams = 1
*.lidarFrontLeft.bridging.streamFilter.egress.classifier.mapping = {"SLidarFrontLeft": 0}
*.lidarFrontLeft.bridging.streamFilter.egress.*[0].display-name = "SLidarFrontLeft"
*.lidarFrontRight.bridging.streamFilter.egress.numStreams = 1
*.lidarFrontRight.bridging.streamFilter.egress.classifier.mapping = {"SLidarFrontRight": 0}
*.lidarFrontRight.bridging.streamFilter.egress.*[0].display-name = "SLidarFrontRight"
*.lidarRearLeft.bridging.streamFilter.egress.numStreams = 1
*.lidarRearLeft.bridging.streamFilter.egress.classifier.mapping = {"SLidarRearLeft": 0}
*.lidarRearLeft.bridging.streamFilter.egress.*[0].display-name = "SLidarRearLeft"
*.lidarRearRight.bridging.streamFilter.egress.numStreams = 1
*.lidarRearRight.bridging.streamFilter.egress.classifier.mapping = {"SLidarRearRight": 0}
*.lidarRearRight.bridging.streamFilter.egress.*[0].display-name = "SLidarRearRight"
*.lidar*.bridging.streamFilter.egress.meter[0].committedInformationRate = ${lidarCIR = 125}Mbps
*.lidar*.bridging.streamFilter.egress.meter[0].committedBurstSize = ${lidarCBS = 1936}B 
*.lidar*.bridging.streamFilter.egress.meter[0].packetOverheadLength = ${deviceOverhead}B 

*.lidar*.eth[0].macLayer.queue.queue[5].typename = "EligibilityTimeQueue"
*.lidar*.eth[0].macLayer.queue.transmissionSelectionAlgorithm[5].typename = "EligibilityTimeGate"


# ATS on switches
*.switch*.bridging.directionReverser.reverser.excludeEncapsulationProtocols = ["ieee8021qctag"]

*.switch*.hasIngressTrafficFiltering = true 
*.switch*.bridging.streamFilter.ingress.typename = "Ieee8021qcrFilter"

# the overhead is the same everywhere
*.switch*.bridging.streamFilter.ingress.meter[*].packetOverheadLength = ${switchOverhead = 32}B 

*.switch*.eth[*].macLayer.queue.queue[5].typename = "EligibilityTimeQueue"
*.switch*.eth[*].macLayer.queue.transmissionSelectionAlgorithm[5].typename = "EligibilityTimeGate"

# switchFrontRight
*.switchFrontRight.bridging.streamFilter.ingress.numStreams = 5

*.switchFrontRight.bridging.streamFilter.ingress.classifier.mapping = {"SVideoFront": 0,
																	  "SVideoRear1": 1,
																	  "SLidarFrontLeft1": 2,
																	  "SLidarFrontRight": 3,
																	  "SLidarRearLeft1": 4}

*.switchFrontRight.bridging.streamFilter.ingress.*[0].display-name = "SVideoFront" # from eth2
*.switchFrontRight.bridging.streamFilter.ingress.*[1].display-name = "SVideoRear1" # from eth0
*.switchFrontRight.bridging.streamFilter.ingress.*[2].display-name = "SLidarFrontLeft1" # from eth0 
*.switchFrontRight.bridging.streamFilter.ingress.*[3].display-name = "SLidarFrontRight" # from eth3
*.switchFrontRight.bridging.streamFilter.ingress.*[4].display-name = "SLidarRearLeft1" # from eth0 

*.switchFrontRight.bridging.streamFilter.ingress.streamFilter[0..1].packetFilter = expr(totalLength <= 1426B)
*.switchFrontRight.bridging.streamFilter.ingress.streamFilter[2..4].packetFilter = expr(totalLength <= 1928B)

*.switchFrontRight.bridging.streamFilter.ingress.meter[0..1].committedInformationRate = ${videoCIR}Mbps
*.switchFrontRight.bridging.streamFilter.ingress.meter[0..1].committedBurstSize = ${videoCBS}B

*.switchFrontRight.bridging.streamFilter.ingress.meter[2..4].committedInformationRate = ${lidarCIR}Mbps
*.switchFrontRight.bridging.streamFilter.ingress.meter[2..4].committedBurstSize = ${lidarCBS}B

#TODO: set maxResidenceTime to useful values
*.switchFrontRight.bridging.streamFilter.ingress.meter[0].maxResidenceTime = 10ms # from eth2
*.switchFrontRight.bridging.streamFilter.ingress.meter[1..2].maxResidenceTime = 10ms # from eth0 (same as meter[4])
*.switchFrontRight.bridging.streamFilter.ingress.meter[4].maxResidenceTime = 10ms # from eth0 (same as meter[1..2])
*.switchFrontRight.bridging.streamFilter.ingress.meter[3].maxResidenceTime = 10ms # from eth3

# switchFrontLeft
*.switchFrontLeft.bridging.streamFilter.ingress.numStreams = 5

*.switchFrontLeft.bridging.streamFilter.ingress.classifier.mapping = {"SVideoFront2": 0,
																	 "SVideoRear1": 1,
																	 "SLidarFrontLeft": 2,
																	 "SLidarFrontRight2": 3,
																	 "SLidarRearLeft1": 4}

*.switchFrontLeft.bridging.streamFilter.ingress.*[0].display-name = "SVideoFront2" # from eth0
*.switchFrontLeft.bridging.streamFilter.ingress.*[1].display-name = "SVideoRear1" # from eth1
*.switchFrontLeft.bridging.streamFilter.ingress.*[2].display-name = "SLidarFrontLeft" # from eth2
*.switchFrontLeft.bridging.streamFilter.ingress.*[3].display-name = "SLidarFrontRight2" # from eth0
*.switchFrontLeft.bridging.streamFilter.ingress.*[4].display-name = "SLidarRearLeft1" # from eth1

*.switchFrontLeft.bridging.streamFilter.ingress.streamFilter[0..1].packetFilter = expr(totalLength <= 1426B)
*.switchFrontLeft.bridging.streamFilter.ingress.streamFilter[2..4].packetFilter = expr(totalLength <= 1928B)

*.switchFrontLeft.bridging.streamFilter.ingress.meter[0..1].committedInformationRate = ${videoCIR}Mbps
*.switchFrontLeft.bridging.streamFilter.ingress.meter[0..1].committedBurstSize = ${videoCBS}B

*.switchFrontLeft.bridging.streamFilter.ingress.meter[2..4].committedInformationRate = ${lidarCIR}Mbps
*.switchFrontLeft.bridging.streamFilter.ingress.meter[2..4].committedBurstSize = ${lidarCBS}B

*.switchFrontLeft.bridging.streamFilter.ingress.meter[0].maxResidenceTime = 10ms # from eth0 (same as meter[3])
*.switchFrontLeft.bridging.streamFilter.ingress.meter[3].maxResidenceTime = 10ms # from eth0 (same as meter[0])
*.switchFrontLeft.bridging.streamFilter.ingress.meter[1].maxResidenceTime = 10ms # from eth1 (same as meter[4])
*.switchFrontLeft.bridging.streamFilter.ingress.meter[4].maxResidenceTime = 10ms # from eth1 (same as meter[1])
*.switchFrontLeft.bridging.streamFilter.ingress.meter[2].maxResidenceTime = 10ms # from eth2

# switchRearRight
*.switchRearRight.bridging.streamFilter.ingress.numStreams = 11

*.switchRearRight.bridging.streamFilter.ingress.classifier.mapping = {"SVideoFront1": 0, "SVideoFront2": 1,
																	 "SVideoRear1": 2, "SVideoRear2": 3,
																	 "SLidarFrontLeft1": 4, "SLidarFrontLeft2": 5,
																	 "SLidarFrontRight1": 6, "SLidarFrontRight2": 7,
																	 "SLidarRearLeft1": 8, "SLidarRearLeft2": 9,
																	 "SLidarRearRight": 10}

*.switchRearRight.bridging.streamFilter.ingress.*[0].display-name = "SVideoFront1" # from eth0 
*.switchRearRight.bridging.streamFilter.ingress.*[1].display-name = "SVideoFront2" # from eth1 
*.switchRearRight.bridging.streamFilter.ingress.*[2].display-name = "SVideoRear1" # from eth0
*.switchRearRight.bridging.streamFilter.ingress.*[3].display-name = "SVideoRear2" # from eth1
*.switchRearRight.bridging.streamFilter.ingress.*[4].display-name = "SLidarFrontLeft1" # from eth0
*.switchRearRight.bridging.streamFilter.ingress.*[5].display-name = "SLidarFrontLeft2" # from eth1 
*.switchRearRight.bridging.streamFilter.ingress.*[6].display-name = "SLidarFrontRight1" # from eth0
*.switchRearRight.bridging.streamFilter.ingress.*[7].display-name = "SLidarFrontRight2" # from eth1
*.switchRearRight.bridging.streamFilter.ingress.*[8].display-name = "SLidarRearLeft1" # from eth0
*.switchRearRight.bridging.streamFilter.ingress.*[9].display-name = "SLidarRearLeft2" # from eth1
*.switchRearRight.bridging.streamFilter.ingress.*[10].display-name = "SLidarRearRight" # from eth4 

*.switchRearRight.bridging.streamFilter.ingress.streamFilter[0..3].packetFilter = expr(totalLength <= 1426B)
*.switchRearRight.bridging.streamFilter.ingress.streamFilter[4..10].packetFilter = expr(totalLength <= 1928B)

*.switchRearRight.bridging.streamFilter.ingress.meter[0..3].committedInformationRate = ${videoCIR}Mbps
*.switchRearRight.bridging.streamFilter.ingress.meter[0..3].committedBurstSize = ${videoCBS}B

*.switchRearRight.bridging.streamFilter.ingress.meter[4..10].committedInformationRate = ${lidarCIR}Mbps
*.switchRearRight.bridging.streamFilter.ingress.meter[4..10].committedBurstSize = ${lidarCBS}B
 
# from eth0
*.switchRearRight.bridging.streamFilter.ingress.meter[0].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[2].maxResidenceTime = 10ms
*.switchRearRight.bridging.streamFilter.ingress.meter[4].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[6].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[8].maxResidenceTime = 10ms 
# from eth1
*.switchRearRight.bridging.streamFilter.ingress.meter[1].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[3].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[5].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[7].maxResidenceTime = 10ms 
*.switchRearRight.bridging.streamFilter.ingress.meter[9].maxResidenceTime = 10ms  
# from eth4
*.switchRearRight.bridging.streamFilter.ingress.meter[10].maxResidenceTime = 10ms

# switchRearLeft
*.switchRearLeft.bridging.streamFilter.ingress.numStreams = 5

*.switchRearLeft.bridging.streamFilter.ingress.classifier.mapping = {"SVideoFront2": 0,
																	 "SVideoRear": 1,
																	 "SLidarFrontLeft2": 2,
																	 "SLidarFrontRight2": 3,
																	 "SLidarRearLeft": 4}

*.switchRearLeft.bridging.streamFilter.ingress.*[0].display-name = "SVideoFront2" # from eth1 
*.switchRearLeft.bridging.streamFilter.ingress.*[1].display-name = "SVideoRear" # from eth2
*.switchRearLeft.bridging.streamFilter.ingress.*[2].display-name = "SLidarFrontLeft2" # from eth1
*.switchRearLeft.bridging.streamFilter.ingress.*[3].display-name = "SLidarFrontRight2" # from eth1
*.switchRearLeft.bridging.streamFilter.ingress.*[4].display-name = "SLidarRearLeft" # from eth3


*.switchRearLeft.bridging.streamFilter.ingress.streamFilter[0..1].packetFilter = expr(totalLength <= 1426B)

*.switchRearLeft.bridging.streamFilter.ingress.streamFilter[2..4].packetFilter = expr(totalLength <= 1928B)

*.switchRearLeft.bridging.streamFilter.ingress.meter[0..1].committedInformationRate = ${videoCIR}Mbps
*.switchRearLeft.bridging.streamFilter.ingress.meter[0..1].committedBurstSize = ${videoCBS}B

*.switchRearLeft.bridging.streamFilter.ingress.meter[2..4].committedInformationRate = ${lidarCIR}Mbps
*.switchRearLeft.bridging.streamFilter.ingress.meter[2..4].committedBurstSize = ${lidarCBS}B 

*.switchRearLeft.bridging.streamFilter.ingress.meter[0].maxResidenceTime = 10ms # from eth1 (same as meter[2..3])
*.switchRearLeft.bridging.streamFilter.ingress.meter[2..3].maxResidenceTime = 10ms # from eth1 (same as meter[0])
*.switchRearLeft.bridging.streamFilter.ingress.meter[1].maxResidenceTime = 10ms # from eth2
*.switchRearLeft.bridging.streamFilter.ingress.meter[4].maxResidenceTime = 10ms # from eth3
