
# This file contains configuration blocks, that are reused in multiple simulations
[General]
# Needed for all simulations
# disable local multicast loop
**.udp.defaultMulticastLoop = false

# disable automatic MAC forwarding table configuration
*.macForwardingTableConfigurator.typename = ""
*.s*.macTable.agingTime = 1200s
*.s*.bridging.interfaceRelay.learner.typename = ""

*.s*.streamCoder.typename = "StreamCoderLayer"

*.s*.hasOutgoingStreams = true
*.s*.hasIncomingStreams = true

*.*.hasStreamRedundancy = true

#*.Listener.ethernet.macHeaderChecker.promiscuous = true ??


[_streamConfigs]
description = "[Block] Configurations for stream transmission by network node."
# === Talker (Source) ===
*.talker.hasOutgoingStreams = true

*.talker.numApps = 3

*.talker.app[0].typename = "UdpSourceApp"
*.talker.app[0].display-name = "Blue"
*.talker.app[0].io.destAddress = "224.0.0.1"
*.talker.app[0].io.destPort = 1001
*.talker.app[0].io.localPort = 2001
*.talker.app[0].source.typename = "CyclicPacketSource"
*.talker.app[0].source.initialProductionOffset = ${d = 0.00004}s
*.talker.app[0].source.packetLength = ${packetLen = 61}B
*.talker.app[0].source.productionIntervals = "0.00005 0.00009"
*.talker.app[0].source.packetNameFormat = "BLUE-%c"

*.talker.app[1].typename = "UdpSourceApp"
*.talker.app[1].display-name = "Red"
*.talker.app[1].io.destAddress = "224.0.0.2"
*.talker.app[1].io.destPort = 1002
*.talker.app[1].io.localPort = 2002
*.talker.app[1].source.typename = "CyclicPacketSource"
*.talker.app[1].source.initialProductionOffset = ${I=0.00005}s + ${e = 0.00001}s
*.talker.app[1].source.packetLength = ${packetLen}B
*.talker.app[1].source.productionIntervals = "0.00005 0.00009"
*.talker.app[1].source.packetNameFormat = "RED-%c"

*.talker.app[2].typename = "UdpSourceApp"
*.talker.app[2].display-name = "Orange"
*.talker.app[2].io.destAddress = "224.0.0.3"
*.talker.app[2].io.destPort = 1003
*.talker.app[2].io.localPort = 2003
*.talker.app[2].source.typename = "CyclicPacketSource"
*.talker.app[2].source.initialProductionOffset =  2*${I}s+2*${e}s
*.talker.app[2].source.packetLength = ${packetLen}B 
*.talker.app[2].source.productionIntervals = "0.00005 0.00009"
*.talker.app[2].source.packetNameFormat = "ORANGE-%c"

*.talker.bridging.streamIdentifier.identifier.mapping = [
	{stream: "Blue", packetFilter: expr(udp.destPort == 1001), sequenceNumbering: true},
	{stream: "Red", packetFilter: expr(udp.destPort == 1002), sequenceNumbering: true},
	{stream: "Orange", packetFilter: expr(udp.destPort == 1003), sequenceNumbering: true}]

*.talker.bridging.streamCoder.encoder.mapping = [
	{stream: "Blue", pcp: 4, vlan:0},
	{stream: "Red", pcp: 4, vlan:0},
	{stream: "Orange", pcp: 4, vlan:0}]

# === Listener (Destination) ====
*.listener.hasIncomingStreams = true

*.listener.ethernet.macHeaderChecker.promiscuous = true

*.listener.numApps = 3

*.listener.app[0].typename = "UdpSinkApp"
*.listener.app[0].display-name = "Blue"
*.listener.app[0].io.multicastAddresses = ["224.0.0.1"]
*.listener.app[0].io.localPort = 1001

*.listener.app[1].typename = "UdpSinkApp"
*.listener.app[1].display-name = "Red"
*.listener.app[1].io.multicastAddresses = ["224.0.0.2"]
*.listener.app[1].io.localPort = 1002

*.listener.app[2].typename = "UdpSinkApp"
*.listener.app[2].display-name = "Orange"
*.listener.app[2].io.multicastAddresses = ["224.0.0.3"]
*.listener.app[2].io.localPort = 1003

*.listener.bridging.streamCoder.decoder.mapping = [
	{stream: "Blue", interface: "eth0", destination: "01-00-5E-00-00-01", pcp: 4},
	{stream: "Red", interface: "eth0", destination: "01-00-5E-00-00-02", pcp: 4},
	{stream: "Orange", interface: "eth0", destination: "01-00-5E-00-00-03", pcp: 4}]

# === Switch0 (FRER splitting) ===
*.switch0.bridging.streamRelay.typename = "StreamRelayLayer"

*.switch0.macTable.forwardingTable = [
	{address: "01-00-5E-00-00-01", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-01", vlan: 1, interface: "eth2"}, # Blue over sPathB
	{address: "01-00-5E-00-00-02", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-03", vlan:0, interface: "eth1"}]

*.switch0.bridging.streamCoder.decoder.mapping = [
	{stream: "Blue", interface: "eth0", destination: "01-00-5E-00-00-01", pcp:4},
	{stream: "Red", interface: "eth0", destination: "01-00-5E-00-00-02", pcp:4},
	{stream: "Orange", interface: "eth0", destination: "01-00-5E-00-00-03", pcp:4}]

*.switch0.bridging.streamCoder.encoder.mapping = [
	{stream: "BlueA", pcp: 4, vlan: 0},
	{stream: "BlueB", pcp: 4, vlan: 1},
	{stream: "Red", pcp: 4, vlan: 0},
	{stream: "Orange", pcp: 4, vlan: 0}]

*.switch0.bridging.streamRelay.splitter.mapping = {Blue: ["BlueA", "BlueB"]}

# === SwitchL* (Long path) ===
# all 4 switches have identical configurations
*.switchL*.macTable.forwardingTable = [
	{address: "01-00-5E-00-00-01", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-02", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-03", vlan:0, interface: "eth1"}]

*.switchL*.bridging.streamCoder.decoder.mapping = [
	{stream: "BlueA", interface: "eth0", destination: "01-00-5E-00-00-01", pcp:4},
	{stream: "Red", interface: "eth0", destination: "01-00-5E-00-00-02", pcp:4},
	{stream: "Orange", interface: "eth0", destination: "01-00-5E-00-00-03", pcp:4}]

*.switchL*.bridging.streamCoder.encoder.mapping = [
	{stream: "BlueA", pcp: 4, vlan: 0},
	{stream: "Red", pcp: 4, vlan: 0},
	{stream: "Orange", pcp: 4, vlan: 0}]

# === SwitchS1 (Short path) ===
# dropping odd numbered packets of blue
*.switchS1.hasIngressTrafficFiltering = true
*.switchS1.bridging.streamFilter.ingress.numStreams = 1
*.switchS1.bridging.streamFilter.ingress.classifier.mapping = {"BlueB": 0}
*.switchS1.bridging.streamFilter.ingress.meter[0].typename = "OmittedPacketMeter"
*.switchS1.bridging.streamFilter.ingress.filter[0].typename = "ContentBasedFilter"
*.switchS1.bridging.streamFilter.ingress.filter[0].packetFilter = expr(name =~ '*1' || name =~ '*3' || name =~ '*5'
																	|| name =~ '*7' || name =~ '*9')

*.switchS1.macTable.forwardingTable = [
	{address: "01-00-5E-00-00-01", vlan:1, interface: "eth1"}]

*.switchS1.bridging.streamCoder.decoder.mapping = [
	{stream: "BlueB", interface: "eth0", destination: "01-00-5E-00-00-01", pcp:4}]

*.switchS1.bridging.streamCoder.encoder.mapping = [
	{stream: "BlueB", pcp: 4, vlan: 1}]

# === Switch1 (FRER merger) ===
*.switch1.bridging.streamRelay.typename = "StreamRelayLayer"

*.switch1.macTable.forwardingTable = [
	{address: "01-00-5E-00-00-01", vlan:0, interface: "eth0"},
	{address: "01-00-5E-00-00-02", vlan:0, interface: "eth0"},
	{address: "01-00-5E-00-00-03", vlan:0, interface: "eth0"}]

*.switch1.bridging.streamCoder.decoder.mapping = [
	{stream: "BlueA", interface: "eth1", destination: "01-00-5E-00-00-01", pcp:4},
	{stream: "BlueB", interface: "eth2", destination: "01-00-5E-00-00-01", pcp:4},
	{stream: "Red", interface: "eth1", destination: "01-00-5E-00-00-02", pcp:4},
	{stream: "Orange", interface: "eth1", destination: "01-00-5E-00-00-03", pcp:4}]

*.switch1.bridging.streamCoder.encoder.mapping = [
	{stream: "Blue", pcp: 4, vlan: 0},
	{stream: "Red", pcp: 4, vlan: 0},
	{stream: "Orange", pcp: 4, vlan: 0}]

*.switch1.bridging.streamRelay.merger.mapping = {BlueA: "Blue", BlueB: "Blue"}

# === Switch2 (causes unbounded latencies, if ATS is used here) ===
*.switch2.macTable.forwardingTable = [
	{address: "01-00-5E-00-00-01", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-02", vlan:0, interface: "eth1"},
	{address: "01-00-5E-00-00-03", vlan:0, interface: "eth1"}]

*.switch2.bridging.streamCoder.decoder.mapping = [
	{stream: "Blue", interface: "eth0", destination: "01-00-5E-00-00-01", pcp:4},
	{stream: "Red", interface: "eth0", destination: "01-00-5E-00-00-02", pcp:4},
	{stream: "Orange", interface: "eth0", destination: "01-00-5E-00-00-03", pcp:4}]

*.switch2.bridging.streamCoder.encoder.mapping = [
	{stream: "Blue", pcp: 4, vlan: 0},
	{stream: "Red", pcp: 4, vlan: 0},
	{stream: "Orange", pcp: 4, vlan: 0}]

[_delayLongPath]
description = "[Block] Adds very small delay to frames on the long path, such that the order of arrival on switch1 is as needed regardless of minor timing inconsitencies."

*.switchL4.eth[*].processingDelayLayer.typename = "ProcessingDelayLayer"
*.switchL4.eth[*].processingDelayLayer.egress.delay = 0.00001s
*.switchL4.eth[*].processingDelayLayer.egress.bitrate = inf bps
*.switchL4.eth[*].processingDelayLayer.ingress.delay = 0s
*.switchL4.eth[*].processingDelayLayer.ingress.bitrate = inf bps

[_ATSonSwitch2]
description = "[Block] Implements ATS on switch2. Causes unbounded latencies."

*.switch2.hasEgressTrafficShaping = true
*.switch2.bridging.directionReverser.reverser.excludeEncapsulationProtocols = ["ieee8021qctag"]
*.switch2.eth[*].macLayer.queue.numTrafficClasses = 1

*.switch2.eth[*].macLayer.queue.queue[*].typename = "EligibilityTimeQueue"
*.switch2.eth[*].macLayer.queue.transmissionSelectionAlgorithm[*].typename = "EligibilityTimeGate"

*.switch2.hasIngressTrafficFiltering = true
*.switch2.bridging.streamFilter.ingress.typename = "ATSIeee8021qFilter"

*.switch2.bridging.streamFilter.ingress.numStreams = 3
*.switch2.bridging.streamFilter.ingress.classifier.mapping = {"Blue": 0, "Red": 1, "Orange": 2}

# = ATS parameters =
# The same for all streams
*.switch2.bridging.streamFilter.ingress.meter[*].committedInformationRate = 20Mbps
*.switch2.bridging.streamFilter.ingress.meter[*].committedBurstSize = 125B 

*.switch2.bridging.streamFilter.ingress.meter[*].packetOverheadLength = 36B 

[_ATSinNetwork]
description = "[Block] ATS on all switches in the network."

*.switch*.hasEgressTrafficShaping = true
*.switch*.bridging.directionReverser.reverser.excludeEncapsulationProtocols = ["ieee8021qctag"]
*.switch*.eth[*].macLayer.queue.numTrafficClasses = 1

*.switch*.eth[*].macLayer.queue.queue[*].typename = "EligibilityTimeQueue"
*.switch*.eth[*].macLayer.queue.transmissionSelectionAlgorithm[*].typename = "EligibilityTimeGate"

*.switch*.hasIngressTrafficFiltering = true
*.switch*.bridging.streamFilter.ingress.typename = "ATSIeee8021qFilter"

# = Mapping depends on the position in the network =
# Switch with FRER splitting: 'Blue' frames are first assigned an eligibility time and then duplicated
*.switch0.bridging.streamFilter.ingress.numStreams = 3
*.switch0.bridging.streamFilter.ingress.classifier.mapping = {"Blue": 0, "Red": 1, "Orange": 2}
# Long path: has 'BlueA', 'Red', and 'Orange' streams
*.switchL*.bridging.streamFilter.ingress.numStreams = 3
*.switchL*.bridging.streamFilter.ingress.classifier.mapping = {"BlueA": 0, "Red": 1, "Orange": 2}
# Short path: has only 'BlueB' stream
*.switchS1.bridging.streamFilter.ingress.numStreams = 1
*.switchS1.bridging.streamFilter.ingress.classifier.mapping = {"BlueB": 0}
# Switch with FRER merging: 'BlueA' and 'BlueB' are assigned their eligibility times independently and merged afterwards
*.switch1.bridging.streamFilter.ingress.numStreams = 4
*.switch1.bridging.streamFilter.ingress.classifier.mapping = {"BlueA": 0, "BlueB": 1, "Red": 2, "Orange": 3}
# Switch with ATS causing unbounded latencies
*.switch2.bridging.streamFilter.ingress.numStreams = 3
*.switch2.bridging.streamFilter.ingress.classifier.mapping = {"Blue": 0, "Red": 1, "Orange": 2}

# = ATS parameters = 
# The same for all streams and switches
*.switch*.bridging.streamFilter.ingress.meter[*].committedInformationRate = 20Mbps
*.switch*.bridging.streamFilter.ingress.meter[*].committedBurstSize = 125B 

*.switch*.bridging.streamFilter.ingress.meter[*].packetOverheadLength = 36B

# = Packet drops on short path = 
# functionality moved to different filter module for the combination with ATS
*.switchS1.bridging.streamFilter.ingress.gateFilter[0].typename ="MultiPacketFilter"
*.switchS1.bridging.streamFilter.ingress.gateFilter[0].numFilters = 2
*.switchS1.bridging.streamFilter.ingress.gateFilter[0].filter[0].typename = "ContentBasedFilter"
*.switchS1.bridging.streamFilter.ingress.gateFilter[0].filter[0].packetFilter = expr(name =~ '*1' || name =~ '*3' || name =~ '*5'
																	|| name =~ '*7' || name =~ '*9')
*.switchS1.bridging.streamFilter.ingress.gateFilter[0].filter[1].typename = "BackPressureBasedFilter"


[_mrtSetOnSwitch2]
description = "[Block] Sets a value for MaxResidenceTime for ATS on switch2."
*.switch2.bridging.streamFilter.ingress.meter[*].maxResidenceTime = 0.0003s 

[_incrCirCbsOnSwitch2]
description = "[Block] Doubles the values of CommittedInformationRate and CommittedBurstSize for stream 'BLUE' on switch2."
*.switch2.hasEgressTrafficShaping = true
*.switch2.bridging.directionReverser.reverser.excludeEncapsulationProtocols = ["ieee8021qctag"]
*.switch2.eth[*].macLayer.queue.numTrafficClasses = 1

*.switch2.eth[*].macLayer.queue.queue[*].typename = "EligibilityTimeQueue"
*.switch2.eth[*].macLayer.queue.transmissionSelectionAlgorithm[*].typename = "EligibilityTimeGate"

*.switch2.hasIngressTrafficFiltering = true
*.switch2.bridging.streamFilter.ingress.typename = "ATSIeee8021qFilter"

*.switch2.bridging.streamFilter.ingress.numStreams = 3
*.switch2.bridging.streamFilter.ingress.classifier.mapping = {"Blue": 0, "Red": 1, "Orange": 2}

*.switch2.bridging.streamFilter.ingress.meter[0].committedInformationRate = 40Mbps
*.switch2.bridging.streamFilter.ingress.meter[0].committedBurstSize = 250B 

*.switch2.bridging.streamFilter.ingress.meter[1..2].committedInformationRate = 20Mbps
*.switch2.bridging.streamFilter.ingress.meter[1..2].committedBurstSize = 125B 

*.switch2.bridging.streamFilter.ingress.meter[*].packetOverheadLength = 36B 

