[General]

include configs.ini


[_visualisation]
description = "[Block] Visualises packet transmission and drops."

*.visualizer.typename = "IntegratedMultiCanvasVisualizer"

# visualize dropped packets
*.visualizer.numPacketDropVisualizers = 3
*.visualizer.packetDropVisualizer[*].displayPacketDrops = true
*.visualizer.packetDropVisualizer[*].fadeOutTime = 2s
*.visualizer.packetDropVisualizer[0].packetFilter = "BLUE*"
*.visualizer.packetDropVisualizer[0].iconTintColor = "blue"
*.visualizer.packetDropVisualizer[1].packetFilter = "RED*"
*.visualizer.packetDropVisualizer[1].iconTintColor = "red"
*.visualizer.packetDropVisualizer[2].packetFilter = "ORANGE*"
*.visualizer.packetDropVisualizer[2].iconTintColor = "orange"

# visualize packet transmission
# disable "Animate messages" in Simulation for better visibility
*.visualizer.numChannelVisualizers = 3
*.visualizer.channelVisualizer[*].displayChannelActivity = true
*.visualizer.channelVisualizer[*].holdAnimationTime = 0.3s
*.visualizer.channelVisualizer[0].packetFilter = "BLUE*"
*.visualizer.channelVisualizer[0].*Color = "blue"
*.visualizer.channelVisualizer[1].packetFilter = "RED*"
*.visualizer.channelVisualizer[1].*Color = "red"
*.visualizer.channelVisualizer[2].packetFilter = "ORANGE*"
*.visualizer.channelVisualizer[2].*Color = "orange"


[demoBaseline]
network = demoBaseline
description = "Baseline: ATS on switch2. Unbounded latencies."
extends = _streamConfigs, _ATSonSwitch2, _delayLongPath

[demoBaseline_visual]
extends = demoBaseline, _visualisation


[demoModification1]
network = demoModification1
description = "Modification 1: No ATS anywhere. Bounded latencies."
extends = _streamConfigs, _delayLongPath

[demoModification1_visual]
extends = demoModification1, _visualisation

[demoModification2]
network = demoModification2
description = "Modification 2: ATS on all switches. Unbounded latencies."
extends = _streamConfigs, _ATSinNetwork, _delayLongPath

[demoModification2_visual]
extends = demoModification2, _visualisation

[demoModification3]
network = demoModification3
description = "Modification 3: ATS on switch2, mrt configured. Bounded latencies, frame loss."
extends = _streamConfigs, _delayLongPath, _ATSonSwitch2, _mrtSetOnSwitch2

[demoModification3_visual]
extends = demoModification3, _visualisation

[demoModification4]
network = demoModification4
description = "Modification 4: ATS on switch2, cir and cbs doubled. Bounded latencies."
extends = _streamConfigs, _delayLongPath, _incrCirCbsOnSwitch2

[demoModification4_visual]
extends = demoModification4, _visualisation






